# Generated by Django 5.0.1 on 2024-03-04 06:08

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='solicitudprestamo',
            options={'ordering': ['-fecha_de_prestamo'], 'verbose_name': 'Solicitud de Préstamo', 'verbose_name_plural': 'Solicitudes de Préstamo'},
        ),
        migrations.RenameField(
            model_name='solicitudprestamo',
            old_name='fecha_prestamo',
            new_name='fecha_de_prestamo',
        ),
        migrations.RenameField(
            model_name='solicitudprestamo',
            old_name='devuelto',
            new_name='ha_sido_devuelto',
        ),
        migrations.RenameField(
            model_name='solicitudprestamo',
            old_name='soporte',
            new_name='soporte_prestado',
        ),
        migrations.RemoveField(
            model_name='solicitudprestamo',
            name='empleado_receptor',
        ),
        migrations.RemoveField(
            model_name='solicitudprestamo',
            name='empleado_solicitante',
        ),
        migrations.RemoveField(
            model_name='solicitudprestamo',
            name='fecha_devolucion',
        ),
        migrations.RemoveField(
            model_name='solicitudprestamo',
            name='precio_prestamo',
        ),
        migrations.RemoveField(
            model_name='solicitudprestamo',
            name='recargo',
        ),
        migrations.AddField(
            model_name='solicitudprestamo',
            name='costo_del_prestamo',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.01000000000000000020816681711721685132943093776702880859375'), max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
        migrations.AddField(
            model_name='solicitudprestamo',
            name='dias_para_devolucion',
            field=models.PositiveSmallIntegerField(default=django.utils.timezone.now, validators=[django.core.validators.MinValueValidator(1)]), # type: ignore
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solicitudprestamo',
            name='empleado_que_solicita',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, related_name='prestamos_realizados', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
