# Generated by Django 5.0.1 on 2024-03-05 14:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0003_remove_solicitudprestamo_empleado_que_solicita'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudprestamo',
            name='dias_para_devolucion',
            field=models.PositiveSmallIntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='solicitudprestamo',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
