# Generated by Django 5.0.1 on 2024-03-06 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0006_alter_solicitudprestamo_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solicitudprestamo',
            old_name='fecha_entregado',
            new_name='fecha_de_devolucion',
        ),
        migrations.RenameField(
            model_name='solicitudprestamo',
            old_name='soporte_prestado',
            new_name='soporte',
        ),
    ]
