# Generated by Django 5.0.1 on 2024-02-29 13:36

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soportes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casete',
            name='formato_cinta',
            field=models.CharField(choices=[('VHS', 'VHS'), ('Betamax', 'Betamax'), ('VHS-C', 'VHS-C'), ('Video8', 'Video8'), ('Hi8', 'Hi8'), ('Digital8', 'Digital8'), ('MiniDV', 'MiniDV'), ('MicroMV', 'MicroMV'), ('Blu-ray', 'Blu-ray'), ('UHD Blu-ray', 'UHD Blu-ray')], editable=False, max_length=16),
        ),
        migrations.AlterField(
            model_name='dvd',
            name='tamanio',
            field=models.DecimalField(choices=[(Decimal('4.7'), '4.7 GB'), (Decimal('8.5'), '8.5 GB')], decimal_places=1, max_digits=4),
        ),
    ]
