# Generated by Django 5.0.1 on 2024-02-29 14:33

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soportes', '0002_alter_casete_formato_cinta_alter_dvd_tamanio'),
    ]

    operations = [
        migrations.AddField(
            model_name='dvd',
            name='espacio_ocupado',
            field=models.DecimalField(blank=True, decimal_places=1, default=Decimal('0'), max_digits=4),
        ),
    ]
