# Generated by Django 5.0.1 on 2024-02-29 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('soportes', '0003_dvd_espacio_ocupado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dvd',
            old_name='tamanio',
            new_name='capacidad',
        ),
        migrations.RemoveField(
            model_name='dvd',
            name='espacio_ocupado',
        ),
    ]
