# Generated by Django 5.0.1 on 2024-02-29 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soportes', '0004_rename_tamanio_dvd_capacidad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casete',
            name='formato_cinta',
            field=models.CharField(choices=[('VHS', 'VHS'), ('Betamax', 'Betamax'), ('VHS-C', 'VHS-C'), ('Video8', 'Video8'), ('Hi8', 'Hi8'), ('Digital8', 'Digital8'), ('MiniDV', 'MiniDV'), ('MicroMV', 'MicroMV'), ('Blu-ray', 'Blu-ray'), ('UHD Blu-ray', 'UHD Blu-ray')], max_length=16),
        ),
    ]
