# Generated by Django 5.0.1 on 2024-03-06 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soportes', '0008_alter_soporte_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soporte',
            name='estado',
            field=models.CharField(choices=[('B', 'Bien'), ('R', 'Regular'), ('M', 'Mal'), ('I', 'Inutilizable')], default='B', max_length=1),
        ),
    ]
