# Generated by Django 5.0.1 on 2024-02-24 22:04

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Soporte',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('costo_adquisicion', models.DecimalField(decimal_places=2, max_digits=5)),
                ('estado', models.CharField(choices=[('B', 'Bien'), ('M', 'Mal'), ('R', 'Regular')], default='B', max_length=1)),
                ('cant_peliculas_grabadas', models.PositiveIntegerField(blank=True, default=0)),
                ('cant_prestamos', models.PositiveIntegerField(default=0)),
                ('disponible', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'soporte',
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('ci', models.CharField(max_length=11, primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=64)),
                ('apellidos', models.CharField(max_length=64)),
                ('edad', models.IntegerField()),
                ('direccion', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'persona',
            },
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=32)),
            ],
            options={
                'db_table': 'genero',
            },
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=32)),
            ],
            options={
                'db_table': 'provincia',
            },
        ),
        migrations.CreateModel(
            name='Casete',
            fields=[
                ('soporte_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='videoclub.soporte')),
                ('formato_cinta', models.CharField(default='VHS', max_length=32)),
                ('cant_peliculas', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'db_table': 'casete',
            },
            bases=('videoclub.soporte',),
        ),
        migrations.CreateModel(
            name='DVD',
            fields=[
                ('soporte_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='videoclub.soporte')),
                ('tamanio', models.DecimalField(choices=[(4.7, '4.7 GB'), (8.5, '8.5 GB')], decimal_places=1, max_digits=4)), # type: ignore
                ('formato_almacenamiento', models.CharField(choices=[('Dato', 'Dato'), ('DVDVideo', 'DVDVideo')], default='Dato', max_length=8)),
            ],
            options={
                'db_table': 'dvd',
            },
            bases=('videoclub.soporte',),
        ),
        migrations.CreateModel(
            name='VCD',
            fields=[
                ('soporte_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='videoclub.soporte')),
                ('marca', models.CharField(default='Indefinido', max_length=32)),
            ],
            options={
                'db_table': 'vcd',
            },
            bases=('videoclub.soporte',),
        ),
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('tamanio', models.DecimalField(decimal_places=1, max_digits=2)),
                ('titulo', models.CharField(max_length=64)),
                ('anio', models.IntegerField()),
                ('duracion', models.IntegerField()),
                ('director', models.CharField(default='Indefinido', max_length=64)),
                ('clasif_edad', models.CharField(choices=[('A', 'Apto para todo publico'), ('B', 'Pelicula para niños mayores de 12'), ('C', 'Pelicula para mayores de 16'), ('D', 'Pelicula para mayores de 18')], default='A', max_length=1)),
                ('estreno', models.BooleanField(default=False)),
                ('genero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peliculas', to='videoclub.genero')),
                ('soporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peliculas', to='videoclub.soporte')),
            ],
            options={
                'db_table': 'pelicula',
            },
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=32)),
                ('provincia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='municipios', to='videoclub.provincia')),
            ],
            options={
                'db_table': 'municipio',
            },
        ),
        migrations.CreateModel(
            name='SolicitudPrestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_prestamo', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fecha_prestamo', models.DateField(auto_now_add=True)),
                ('fecha_devolucion', models.DateField()),
                ('recargo', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5)),
                ('devuelto', models.BooleanField(default=False)),
                ('fecha_entregado', models.DateField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes', to='videoclub.persona')),
                ('soporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videoclub.soporte')),
            ],
            options={
                'db_table': 'solicitud_prestamo',
            },
        ),
        migrations.CreateModel(
            name='VideoClub',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=32)),
                ('direccion', models.CharField(max_length=64)),
                ('telefono', models.CharField(max_length=16)),
                ('cant_soportes', models.PositiveIntegerField(blank=True, default=0)),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videoclub.municipio')),
            ],
            options={
                'db_table': 'videoclub',
            },
        ),
        migrations.AddField(
            model_name='soporte',
            name='videoclub',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videoclub.videoclub'),
        ),
        migrations.AddField(
            model_name='persona',
            name='videoclubs',
            field=models.ManyToManyField(to='videoclub.videoclub'),
        ),
        migrations.CreateModel(
            name='ClienteFijo',
            fields=[
                ('persona', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='videoclub.persona')),
                ('max_soportes_prestados', models.PositiveIntegerField(default=3)),
                ('cant_soportes_alquilados', models.PositiveIntegerField(default=0)),
                ('genero_favorito', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='preferido_por', to='videoclub.genero')),
            ],
            options={
                'db_table': 'cliente_fijo',
            },
        ),
        migrations.CreateModel(
            name='ClienteTemporal',
            fields=[
                ('persona', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='videoclub.persona')),
                ('telefono', models.CharField(max_length=8)),
                ('confianza', models.BooleanField(default=True)),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videoclub.municipio')),
            ],
            options={
                'db_table': 'cliente_temporal',
            },
        ),
    ]
