# Generated by Django 5.0.1 on 2024-02-14 01:56

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Soporte',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('costo', models.DecimalField(decimal_places=2, max_digits=5)),
                ('estado', models.CharField(choices=[('B', 'Bien'), ('M', 'Mal'), ('R', 'Regular')], default='B', max_length=1)),
                ('cant_peliculas', models.PositiveIntegerField(default=1, verbose_name='Cantidad de peliculas en el soporte')),
            ],
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=32)),
            ],
            options={
                'db_table': 'genero',
                'db_table_comment': 'Generos de peliculas',
            },
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Casete',
            fields=[
                ('soporte_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='videoclub.soporte')),
                ('formato', models.CharField(default='VHS', max_length=32)),
                ('cant_peliculas_casete', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'Casete',
            },
            bases=('videoclub.soporte',),
        ),
        migrations.CreateModel(
            name='DVD',
            fields=[
                ('soporte_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='videoclub.soporte')),
                ('tamanio', models.DecimalField(decimal_places=1, default=Decimal('4.7'), max_digits=2)),
                ('formato', models.CharField(choices=[('Dato', 'Dato'), ('DVDVideo', 'DVDVideo')], default='Dato', max_length=8)),
            ],
            options={
                'db_table': 'DVD',
            },
            bases=('videoclub.soporte',),
        ),
        migrations.CreateModel(
            name='VCD',
            fields=[
                ('soporte_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='videoclub.soporte')),
                ('marca', models.CharField(default='Indefinido', max_length=32)),
            ],
            options={
                'db_table': 'VCD',
            },
            bases=('videoclub.soporte',),
        ),
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('tamanio', models.DecimalField(decimal_places=1, max_digits=2)),
                ('titulo', models.CharField(max_length=64)),
                ('anio', models.IntegerField()),
                ('duracion', models.IntegerField()),
                ('director', models.CharField(default='Indefinido', max_length=64)),
                ('clasif_edad', models.CharField(choices=[('A', 'Apto para todo publico'), ('B', 'Pelicula para niños mayores de 12'), ('C', 'Pelicula para mayores de 16'), ('D', 'Pelicula para mayores de 18')], default='A', max_length=1)),
                ('estreno', models.BooleanField(default=False)),
                ('genero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peliculas', to='videoclub.genero')),
                ('soporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peliculas', to='videoclub.soporte')),
            ],
            options={
                'db_table': 'pelicula',
                'db_table_comment': 'Peliculas de los soportes',
            },
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=32)),
                ('provincia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='municipios', to='videoclub.provincia')),
            ],
        ),
        migrations.CreateModel(
            name='VideoClub',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=32)),
                ('direccion', models.CharField(max_length=64)),
                ('telefono', models.CharField(max_length=16)),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videoclub.municipio')),
            ],
            options={
                'db_table': 'videoclub',
                'db_table_comment': 'Gestor de un videoclub',
            },
        ),
        migrations.AddField(
            model_name='soporte',
            name='videoclub',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videoclub.videoclub'),
        ),
        migrations.CreateModel(
            name='ClienteTemporal',
            fields=[
                ('ci', models.BigIntegerField(primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=64)),
                ('apellidos', models.CharField(max_length=64)),
                ('edad', models.IntegerField()),
                ('direccion', models.CharField(max_length=64)),
                ('max_soportes_prestados', models.PositiveIntegerField(default=1)),
                ('telefono', models.CharField(max_length=16)),
                ('confianza', models.BooleanField(default=True)),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videoclub.municipio')),
                ('videoclubs', models.ManyToManyField(to='videoclub.videoclub')),
            ],
            options={
                'db_table': 'cliente_temporal',
                'db_table_comment': 'Clientes temporales del videoclub',
            },
        ),
        migrations.CreateModel(
            name='ClienteFijo',
            fields=[
                ('ci', models.BigIntegerField(primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=64)),
                ('apellidos', models.CharField(max_length=64)),
                ('edad', models.IntegerField()),
                ('direccion', models.CharField(max_length=64)),
                ('max_soportes_prestados', models.PositiveIntegerField(default=3)),
                ('genero_favorito', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='preferido_por', to='videoclub.genero')),
                ('videoclubs', models.ManyToManyField(to='videoclub.videoclub')),
            ],
            options={
                'db_table': 'cliente_fijo',
                'db_table_comment': 'Clientes fijos del videoclub',
            },
        ),
    ]
