# Generated by Django 5.0.1 on 2024-02-14 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoclub', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casete',
            name='cant_peliculas_casete',
        ),
        migrations.RemoveField(
            model_name='soporte',
            name='cant_peliculas',
        ),
        migrations.AddField(
            model_name='soporte',
            name='cant_peliculas_grabadas',
            field=models.PositiveIntegerField(default=0, verbose_name='Cantidad de peliculas en el soporte'),
        ),
        migrations.AddField(
            model_name='soporte',
            name='cant_prestamos',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='soporte',
            name='disponible',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vcd',
            name='cant_max_peliculas',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='videoclub',
            name='cant_soportes',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='clientetemporal',
            name='telefono',
            field=models.CharField(max_length=8),
        ),
    ]
