# Generated by Django 5.0.1 on 2024-02-25 02:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoclub', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='solicitudprestamo',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prestamos', to='videoclub.persona'),
        ),
        migrations.AlterField(
            model_name='solicitudprestamo',
            name='soporte',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prestamos', to='videoclub.soporte'),
        ),
    ]
