# Generated by Django 5.0.1 on 2024-02-14 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videoclub', '0002_remove_casete_cant_peliculas_casete_and_more'),
    ]

    operations = [
        migrations.AlterModelTableComment(
            name='clientefijo',
            table_comment=None,
        ),
        migrations.AlterModelTableComment(
            name='clientetemporal',
            table_comment=None,
        ),
        migrations.AlterModelTableComment(
            name='genero',
            table_comment=None,
        ),
        migrations.AlterModelTableComment(
            name='pelicula',
            table_comment=None,
        ),
        migrations.AlterModelTableComment(
            name='videoclub',
            table_comment=None,
        ),
    ]
