# Generated by Django 5.0.1 on 2024-02-25 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoclub', '0002_persona_activo_alter_solicitudprestamo_cliente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoclub',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
