# Generated by Django 5.0.1 on 2024-02-25 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoclub', '0003_alter_videoclub_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='persona',
            name='ci',
            field=models.CharField(max_length=11, unique=True),
        ),
        migrations.AlterField(
            model_name='soporte',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
