# Generated by Django 5.0.1 on 2024-02-14 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videoclub', '0003_alter_clientefijo_table_comment_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='municipio',
            table='municipio',
        ),
        migrations.AlterModelTable(
            name='provincia',
            table='provincia',
        ),
    ]
