# Generated by Django 5.0.1 on 2024-02-14 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videoclub', '0004_alter_municipio_table_alter_provincia_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='casete',
            table='casete',
        ),
        migrations.AlterModelTable(
            name='dvd',
            table='dvd',
        ),
        migrations.AlterModelTable(
            name='vcd',
            table='vcd',
        ),
    ]
