# Generated by Django 5.0.1 on 2024-02-25 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoclub', '0004_persona_id_alter_persona_ci_alter_soporte_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelicula',
            name='codigo',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.RemoveField(
            model_name='pelicula',
            name='soporte',
        ),
        migrations.AddField(
            model_name='pelicula',
            name='soporte',
            field=models.ManyToManyField(editable=False, related_name='peliculas', to='videoclub.soporte'),
        ),
    ]
