# Generated by Django 5.0.1 on 2024-02-25 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videoclub', '0005_pelicula_codigo_alter_pelicula_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pelicula',
            name='codigo',
        ),
    ]
