# Generated by Django 5.0.1 on 2024-02-14 04:24

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoclub', '0005_alter_casete_table_alter_dvd_table_alter_vcd_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='casete',
            old_name='formato',
            new_name='formato_cinta',
        ),
        migrations.RenameField(
            model_name='dvd',
            old_name='formato',
            new_name='formato_almacenamiento',
        ),
        migrations.RenameField(
            model_name='soporte',
            old_name='costo',
            new_name='costo_adquisicion',
        ),
        migrations.RemoveField(
            model_name='clientefijo',
            name='apellidos',
        ),
        migrations.RemoveField(
            model_name='clientefijo',
            name='ci',
        ),
        migrations.RemoveField(
            model_name='clientefijo',
            name='direccion',
        ),
        migrations.RemoveField(
            model_name='clientefijo',
            name='edad',
        ),
        migrations.RemoveField(
            model_name='clientefijo',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='clientefijo',
            name='videoclubs',
        ),
        migrations.RemoveField(
            model_name='clientetemporal',
            name='apellidos',
        ),
        migrations.RemoveField(
            model_name='clientetemporal',
            name='ci',
        ),
        migrations.RemoveField(
            model_name='clientetemporal',
            name='direccion',
        ),
        migrations.RemoveField(
            model_name='clientetemporal',
            name='edad',
        ),
        migrations.RemoveField(
            model_name='clientetemporal',
            name='max_soportes_prestados',
        ),
        migrations.RemoveField(
            model_name='clientetemporal',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='clientetemporal',
            name='videoclubs',
        ),
        migrations.RemoveField(
            model_name='vcd',
            name='cant_max_peliculas',
        ),
        migrations.AddField(
            model_name='casete',
            name='cant_peliculas',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='clientefijo',
            name='cant_soportes_alquilados',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dvd',
            name='tamanio',
            field=models.DecimalField(choices=[(4.7, '4.7 GB'), (8.5, '8.5 GB')], decimal_places=1, max_digits=4),
        ),
        migrations.AlterField(
            model_name='soporte',
            name='cant_peliculas_grabadas',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('ci', models.CharField(max_length=11, primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=64)),
                ('apellidos', models.CharField(max_length=64)),
                ('edad', models.IntegerField()),
                ('direccion', models.CharField(max_length=64)),
                ('videoclubs', models.ManyToManyField(to='videoclub.videoclub')),
            ],
        ),
        migrations.AddField(
            model_name='clientefijo',
            name='persona',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='videoclub.persona'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clientetemporal',
            name='persona',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='videoclub.persona'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='SolicitudPrestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_prestamo', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fecha_prestamo', models.DateField(auto_now_add=True)),
                ('fecha_devolucion', models.DateField()),
                ('recargo', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5)),
                ('devuelto', models.BooleanField(default=False)),
                ('fecha_entregado', models.DateField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes', to='videoclub.persona')),
                ('soporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videoclub.soporte')),
            ],
        ),
    ]
