# Generated by Django 5.0.1 on 2024-02-14 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videoclub', '0006_rename_formato_casete_formato_cinta_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='persona',
            table='persona',
        ),
        migrations.AlterModelTable(
            name='solicitudprestamo',
            table='solicitud_prestamo',
        ),
    ]
