# Generated by Django 5.0.1 on 2024-02-14 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videoclub', '0007_alter_persona_table_alter_solicitudprestamo_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='soporte',
            table='soporte',
        ),
    ]
