# Generated by Django 5.0.1 on 2024-03-02 21:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0003_rename_soporte_pelicula_soportes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('Comedia', 'Comedia'), ('Acción', 'Acción'), ('Aventura', 'Aventura'), ('Ciencia Ficción', 'Ciencia Ficción'), ('Drama', 'Drama'), ('Romance', 'Romance'), ('Fantasía', 'Fantasía'), ('Terror', 'Terror'), ('Suspenso', 'Suspenso'), ('Animación', 'Animación'), ('Documental', 'Documental'), ('Musical', 'Musical'), ('Crimen', 'Crimen'), ('Misterio', 'Misterio'), ('Western', 'Western'), ('Histórico', 'Histórico'), ('Guerra', 'Guerra'), ('Biografía', 'Biografía'), ('Fantástico', 'Fantástico'), ('Infantil', 'Infantil')], max_length=64, unique=True)),
            ],
            options={
                'db_table': 'genero',
            },
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='genero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peliculas', to='peliculas.genero'),
        ),
    ]
