# Generated by Django 5.0.1 on 2024-03-04 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0008_remove_pelicula_disponible'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pelicula',
            name='estreno',
        ),
        migrations.AddField(
            model_name='pelicula',
            name='disponible',
            field=models.BooleanField(default=True),
        ),
    ]
