# Generated by Django 5.0.1 on 2024-03-09 22:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('9e99fe4d-0eb6-4de0-b35d-b6b56c5fa0c0'), primary_key=True, serialize=False),
        ),
    ]
