# Generated by Django 5.0.1 on 2024-03-09 22:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('8e6b1d3e-b253-4830-b6a0-0f19670f210c'), primary_key=True, serialize=False),
        ),
    ]
