# Generated by Django 5.0.3 on 2024-03-19 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_user_user_idx'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['first_name', 'last_name', '-is_staff'], 'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
    ]
