# Generated by Django 5.0.1 on 2024-03-08 11:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_user_options_alter_user_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('9715ff27-32eb-42ce-b7df-4ac3b8cfb4ea'), primary_key=True, serialize=False),
        ),
    ]
