# Generated by Django 5.0.1 on 2024-03-09 22:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('88a63f7e-862a-4c79-952a-5d283f6d19b6'), primary_key=True, serialize=False),
        ),
    ]
