# Generated by Django 5.0.1 on 2024-02-26 14:25

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('peliculas', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ci', models.CharField(max_length=11, unique=True)),
                ('nombre', models.CharField(max_length=64)),
                ('apellidos', models.CharField(max_length=64)),
                ('edad', models.PositiveIntegerField()),
                ('municipio', models.CharField(max_length=64)),
                ('direccion', models.CharField(max_length=64)),
                ('telefono', models.CharField(max_length=8)),
                ('activo', models.BooleanField(default=True)),
                ('cant_soportes_alquilados', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)])),
            ],
            options={
                'db_table': 'cliente',
            },
        ),
        migrations.CreateModel(
            name='ClienteTemporal',
            fields=[
                ('persona', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='clientes.cliente')),
                ('max_soportes_prestados', models.PositiveIntegerField(default=1)),
                ('confianza', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'cliente_temporal',
            },
        ),
        migrations.CreateModel(
            name='ClienteFijo',
            fields=[
                ('persona', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='clientes.cliente')),
                ('max_soportes_prestados', models.PositiveIntegerField(default=3)),
                ('genero_favorito', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='preferido_por', to='peliculas.genero')),
            ],
            options={
                'db_table': 'cliente_fijo',
            },
        ),
    ]
