# Generated by Django 5.0.1 on 2024-02-27 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientefijo',
            name='genero_favorito',
            field=models.CharField(blank=True, choices=[('Comedia', 'Comedia'), ('Acción', 'Acción'), ('Aventura', 'Aventura'), ('Ciencia Ficción', 'Ciencia Ficción'), ('Drama', 'Drama'), ('Romance', 'Romance'), ('Fantasía', 'Fantasía'), ('Terror', 'Terror'), ('Suspenso', 'Suspenso'), ('Animación', 'Animación'), ('Documental', 'Documental'), ('Musical', 'Musical'), ('Crimen', 'Crimen'), ('Misterio', 'Misterio'), ('Western', 'Western'), ('Histórico', 'Histórico'), ('Guerra', 'Guerra'), ('Biografía', 'Biografía'), ('Fantástico', 'Fantástico'), ('Infantil', 'Infantil')], default='Indefinido', max_length=64, null=True),
        ),
    ]
