# Generated by Django 5.0.1 on 2024-03-04 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('soportes', '0006_alter_casete_formato_cinta'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='soporte',
            options={'ordering': ['cant_peliculas_grabadas', 'costo_adquisicion', 'estado']},
        ),
    ]
