# Generated by Django 5.0.1 on 2024-02-26 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('videoclub', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=32)),
            ],
            options={
                'db_table': 'genero',
            },
        ),
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tamanio', models.DecimalField(decimal_places=1, max_digits=2)),
                ('titulo', models.CharField(max_length=64)),
                ('anio', models.IntegerField()),
                ('duracion', models.IntegerField()),
                ('director', models.CharField(default='Indefinido', max_length=64)),
                ('clasif_edad', models.CharField(choices=[('A', 'Apto para todo publico'), ('B', 'Pelicula para niños mayores de 12'), ('C', 'Pelicula para mayores de 16'), ('D', 'Pelicula para mayores de 18')], default='A', max_length=1)),
                ('estreno', models.BooleanField(default=False)),
                ('genero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peliculas', to='peliculas.genero')),
                ('soporte', models.ManyToManyField(related_name='peliculas', to='videoclub.soporte')),
            ],
            options={
                'db_table': 'pelicula',
            },
        ),
    ]
