# Generated by Django 5.0.1 on 2024-02-28 21:01

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0002_alter_pelicula_genero_delete_genero'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pelicula',
            name='anio',
        ),
        migrations.AddField(
            model_name='pelicula',
            name='fecha_estreno',
            field=models.DateField(default='1971-12-31', editable=False, help_text='must be format: YYYY-MM-DD'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pelicula',
            name='precio',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('10'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='estreno',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='tamanio',
            field=models.DecimalField(decimal_places=1, max_digits=3),
        ),
    ]
