# Generated by Django 5.0.1 on 2024-02-29 05:37

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('soportes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=64)),
                ('genero', models.CharField(choices=[('Comedia', 'Comedia'), ('Acción', 'Acción'), ('Aventura', 'Aventura'), ('Ciencia Ficción', 'Ciencia Ficción'), ('Drama', 'Drama'), ('Romance', 'Romance'), ('Fantasía', 'Fantasía'), ('Terror', 'Terror'), ('Suspenso', 'Suspenso'), ('Animación', 'Animación'), ('Documental', 'Documental'), ('Musical', 'Musical'), ('Crimen', 'Crimen'), ('Misterio', 'Misterio'), ('Western', 'Western'), ('Histórico', 'Histórico'), ('Guerra', 'Guerra'), ('Biografía', 'Biografía'), ('Fantástico', 'Fantástico'), ('Infantil', 'Infantil')], default='Indefinido', max_length=64)),
                ('duracion', models.IntegerField()),
                ('director', models.CharField(default='Indefinido', max_length=64)),
                ('clasif_edad', models.CharField(choices=[('A', 'Apto para todo publico'), ('B', 'Pelicula para niños mayores de 12'), ('C', 'Pelicula para mayores de 16'), ('D', 'Pelicula para mayores de 18')], default='A', editable=False, max_length=1)),
                ('fecha_estreno', models.DateField(editable=False, help_text='must be format: YYYY-MM-DD')),
                ('estreno', models.BooleanField(blank=True, default=None, null=True)),
                ('tamanio', models.DecimalField(decimal_places=1, max_digits=3)),
                ('precio', models.DecimalField(blank=True, decimal_places=2, default=Decimal('10'), max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01000000000000000020816681711721685132943093776702880859375'))])),
                ('soporte', models.ManyToManyField(related_name='peliculas', to='soportes.soporte')),
            ],
            options={
                'db_table': 'pelicula',
            },
        ),
    ]
