# Generated by Django 5.0.1 on 2024-02-29 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelicula',
            name='disponible',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
