# Generated by Django 5.0.1 on 2024-03-02 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0005_alter_genero_options_alter_pelicula_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pelicula',
            options={'ordering': ['titulo']},
        ),
    ]
