# Generated by Django 5.0.1 on 2024-03-04 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0012_alter_pelicula_fecha_estreno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelicula',
            name='fecha_estreno',
            field=models.DateField(help_text='must be format: YYYY-MM-DD'),
        ),
    ]
