# Generated by Django 5.0.3 on 2024-03-16 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0013_alter_pelicula_fecha_estreno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelicula',
            name='clasif_edad',
            field=models.CharField(choices=[('A', 'Apto para todo publico'), ('B', 'Pelicula para niños mayores de 12'), ('C', 'Pelicula para mayores de 16'), ('D', 'Pelicula para mayores de 18')], default='A', max_length=1),
        ),
    ]
