# Generated by Django 5.0.3 on 2024-03-18 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0014_alter_pelicula_clasif_edad'),
        ('soportes', '0013_soporte_soporte_index'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='pelicula',
            index=models.Index(fields=['titulo', 'genero', 'fecha_estreno'], name='pelicula_idx'),
        ),
    ]
