# Generated by Django 5.0.1 on 2024-03-03 04:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0009_remove_clientefijo_max_soportes_prestados_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invalidacion',
            fields=[
                ('cliente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='clientes.cliente')),
                ('fecha_invalidacion', models.DateField(auto_now_add=True)),
                ('motivo', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name_plural': 'Invalidaciones',
                'db_table': 'invalidado',
                'ordering': ['cliente'],
            },
        ),
    ]
