# Generated by Django 5.0.1 on 2024-03-03 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0011_remove_cliente_confianza'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='provincia',
            field=models.CharField(choices=[('PRI', 'Pinar del Río'), ('ART', 'Artemisa'), ('HAB', 'La Habana'), ('MAY', 'Mayabeque'), ('MTZ', 'Matanzas'), ('CFG', 'Cienfuegos'), ('VCL', 'Villa Clara'), ('SSP', 'Sancti Spíritus'), ('CAV', 'Ciego de Ávila'), ('CMG', 'Camagüey'), ('LTU', 'Las Tunas'), ('GRA', 'Granma'), ('HOL', 'Holguín'), ('SCU', 'Santiago de Cuba'), ('GTM', 'Guantánamo')], max_length=64),
        ),
    ]
