# Generated by Django 5.0.3 on 2024-03-14 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0016_remove_clientefijo_cliente_ptr_clientefijo_cliente'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'ordering': ['-cant_soportes_alquilados', 'nombre', 'apellidos']},
        ),
    ]
