# Generated by Django 5.0.3 on 2024-03-18 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0017_alter_cliente_options'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['ci', 'nombre', 'apellidos'], name='cliente_idx'),
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['activo'], name='cliente_activo_idx'),
        ),
    ]
