# Generated by Django 5.0.1 on 2024-02-29 22:11

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ci', models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator('^\\d{11}$', 'El CI debe tener 11 números sin letras')])),
                ('nombre', models.CharField(max_length=64)),
                ('apellidos', models.CharField(max_length=64)),
                ('edad', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(120, 'La edad no puede ser mayor a 120')])),
                ('provincia', models.CharField(max_length=64)),
                ('direccion', models.CharField(max_length=64)),
                ('telefono', models.CharField(max_length=8)),
                ('activo', models.BooleanField(default=True)),
                ('cant_soportes_alquilados', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)])),
            ],
            options={
                'db_table': 'cliente',
            },
        ),
        migrations.CreateModel(
            name='ClienteFijo',
            fields=[
                ('persona', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='clientes.cliente')),
                ('genero_favorito', models.CharField(blank=True, choices=[('Comedia', 'Comedia'), ('Acción', 'Acción'), ('Aventura', 'Aventura'), ('Ciencia Ficción', 'Ciencia Ficción'), ('Drama', 'Drama'), ('Romance', 'Romance'), ('Fantasía', 'Fantasía'), ('Terror', 'Terror'), ('Suspenso', 'Suspenso'), ('Animación', 'Animación'), ('Documental', 'Documental'), ('Musical', 'Musical'), ('Crimen', 'Crimen'), ('Misterio', 'Misterio'), ('Western', 'Western'), ('Histórico', 'Histórico'), ('Guerra', 'Guerra'), ('Biografía', 'Biografía'), ('Fantástico', 'Fantástico'), ('Infantil', 'Infantil')], default='Indefinido', max_length=64, null=True)),
                ('max_soportes_prestados', models.PositiveIntegerField(default=3)),
            ],
            options={
                'db_table': 'cliente_fijo',
            },
        ),
        migrations.CreateModel(
            name='ClienteTemporal',
            fields=[
                ('persona', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='clientes.cliente')),
                ('max_soportes_prestados', models.PositiveIntegerField(default=1)),
                ('confianza', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'cliente_temporal',
            },
        ),
    ]
