# Generated by Django 5.0.1 on 2024-02-29 04:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_alter_clientefijo_genero_favorito'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='municipio',
            new_name='provincia',
        ),
        migrations.AlterField(
            model_name='cliente',
            name='ci',
            field=models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator('^\\d{11}$', 'El CI debe tener 11 números sin letras')]),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='edad',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(120, 'La edad no puede ser mayor a 120')]),
        ),
    ]
