# Generated by Django 5.0.1 on 2024-03-02 21:23

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_alter_cliente_provincia_alter_cliente_telefono'),
        ('peliculas', '0004_genero_alter_pelicula_genero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='edad',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(120, 'La edad no puede ser mayor a 120'), django.core.validators.MinValueValidator(18, 'La edad no puede ser menor a 18')]),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='provincia',
            field=models.CharField(choices=[('PRI', 'Pinar del Río'), ('ART', 'Artemisa'), ('LHA', 'La Habana'), ('MAY', 'Mayabeque'), ('MTZ', 'Matanzas'), ('CFG', 'Cienfuegos'), ('VCL', 'Villa Clara'), ('SSP', 'Sancti Spíritus'), ('CAV', 'Ciego de Ávila'), ('CMG', 'Camagüey'), ('LTU', 'Las Tunas'), ('GRA', 'Granma'), ('HOL', 'Holguín'), ('SCU', 'Santiago de Cuba'), ('GTM', 'Guantánamo')], max_length=64),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(blank=True, max_length=8, null=True, validators=[django.core.validators.RegexValidator('^5\\d{7}$', 'El teléfono debe tener 8 números y empezar con 5')]),
        ),
        migrations.AlterField(
            model_name='clientefijo',
            name='genero_favorito',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clientes_fijos', to='peliculas.genero'),
        ),
    ]
