# Generated by Django 5.0.1 on 2024-03-03 03:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0007_alter_cliente_provincia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='ci',
            field=models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator('^(?:[0-9]{2})(?:0[1-9]|1[0-2])(?:0[1-9]|[12][0-9]|3[01])[0-9]{5}$', 'El CI debe tener 11 números sin letras')]),
        ),
    ]
