# Generated by Django 5.0.1 on 2024-03-03 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0010_invalidacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='confianza',
        ),
    ]
