# Generated by Django 5.0.1 on 2024-02-29 22:11

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '__first__'),
        ('soportes', '0005_alter_casete_formato_cinta'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudPrestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_prestamo', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('fecha_prestamo', models.DateField(auto_now_add=True)),
                ('fecha_devolucion', models.DateField()),
                ('recargo', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5)),
                ('devuelto', models.BooleanField(default=False)),
                ('fecha_entregado', models.DateField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prestamos', to='clientes.cliente')),
                ('empleado_receptor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prestamos_recibidos', to=settings.AUTH_USER_MODEL)),
                ('empleado_solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prestamos_realizadas', to=settings.AUTH_USER_MODEL)),
                ('soporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prestamos', to='soportes.soporte')),
            ],
            options={
                'db_table': 'solicitud_prestamo',
            },
        ),
    ]
