# Generated by Django 5.0.1 on 2024-03-05 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0002_alter_solicitudprestamo_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitudprestamo',
            name='empleado_que_solicita',
        ),
    ]
