# Generated by Django 5.0.1 on 2024-03-05 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0004_alter_solicitudprestamo_dias_para_devolucion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudprestamo',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
