# Generated by Django 5.0.3 on 2024-03-18 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0017_alter_cliente_options'),
        ('prestamos', '0008_solicitudprestamo_activo'),
        ('soportes', '0012_alter_soporte_options'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='solicitudprestamo',
            index=models.Index(fields=['fecha_de_prestamo'], name='idx_fecha_de_prestamo'),
        ),
        migrations.AddIndex(
            model_name='solicitudprestamo',
            index=models.Index(fields=['cliente', 'soporte'], name='idx_cliente_soporte'),
        ),
    ]
